name: Main
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        subdir: [serve, frontend]
    uses: ./.github/workflows/docker-publish.yml
    with:
      subdir: ${{ matrix.subdir }}
